service: insertUser

provider:
  name: aws
  runtime: nodejs4.3
  deploymentBucket: 123testtestbucket

custom:
  defaultStack: tec2

functions:
  insertUser:
    handler: index.handler
    events:
      - http:
          path: mysql/insertUser
          method: put
    environment:
      HOST:
        Fn::ImportValue:
          Fn::Join:
          - '-'
          - - MySqlPublicIp
            - ${opt:stack, self:custom.defaultStack}
      DATABASE:
        Fn::ImportValue:
          Fn::Join:
          - '-'
          - - MySqlDBName
            - ${opt:stack, self:custom.defaultStack}
      USERNAME:
        Fn::ImportValue:
          Fn::Join:
          - '-'
          - - MySqlDBUsername
            - ${opt:stack, self:custom.defaultStack}
      PASSWORD:
        Fn::ImportValue:
          Fn::Join:
          - '-'
          - - MySqlDBPassword
            - ${opt:stack, self:custom.defaultStack}

